### ISSUE TITLE
size of emoticons are slightly different

### ISSUE THREAD

**Issue by radhakrishnapai** [SebastienThiebaud/STTweetLabel#114]
Hi,

When I use emoticons in a single line of text, the height returned is always slightly bigger than that containing text only.
Found a similar SO question with no answer
http://stackoverflow.com/q/11691495/2954866

Could you please look into the issue?<br>
I want to restrict the height of the label to three lines if the text is too long. Due to different height for emoticons, the text gets truncated.

**Comment by fdiaz** [comment]
I'm experiencing the same issue. Any idea where the problem could be?

**Comment by ashack293** [comment]
Also experiencing this issue in iOS 7.0 - 8.1

**Comment by JayMehta711** [comment]
Hello All, I have face same issue. Please help me how to resolved. I have strict deadline.

**Comment by JayMehta711** [comment]
Finally i got solution .

**Comment by Birju24** [comment]
Thank you @JayMehta711 for find the solution.

**Comment by JayMehta711** [comment]
Hello All,
I have found one solution for that please refer below link.
http://stackoverflow.com/a/29429606/2058242

**Comment by SebastienThiebaud** [comment]
Hello,

`3.1.18` should fix this problem.

**Comment by ashack293** [comment]
Hi Sebastien,

Thanks for addressing this. Unfortunately, the fix has opened another bug with emoticons which I will open as a separate issue.
