### ISSUE TITLE
Issue with emoji character 

### ISSUE THREAD

**Issue by JayMehta711** [SebastienThiebaud/STTweetLabel#129]
Hello All,
When i am use emoji character with STTweetLabel at that time it  will not show properly.Please check my screenshot.
![screen shot 2015-03-31 at 6 08 01 pm](https://cloud.githubusercontent.com/assets/6177191/6919022/ebbbe750-d7d0-11e4-8169-8638867c79cb.png)

**Comment by JayMehta711** [comment]
i have got solution. Please refer below link : http://stackoverflow.com/a/29429606/2058242

**Comment by SebastienThiebaud** [comment]
Hello,

I think this issue is fixed in `3.1.18`. Please reopen if you think that's not the case.
