### ISSUE TITLE
Calling detection block in swift

### ISSUE THREAD

**Issue by dcods22** [SebastienThiebaud/STTweetLabel#133]
Hi I was wondering how to call detection block in swift

I get an error trying 

label.detectionBlock{
    (hotWord:STTweetHotWord, str:NSString, protocolStr:NSString, range:NSRange) -> Void in

}

Thanks

**Comment by SebastienThiebaud** [comment]
The syntax you're using look wrong.

**Comment by dcods22** [comment]
What would the proper syntax be? 

Daniel Cody 
631-365-9940
Daniel.Cody2@Marist.edu
Marist Class of 2015

**Comment by SebastienThiebaud** [comment]
I guess something like

```
        let tweetLabel: STTweetLabel = STTweetLabel()
        tweetLabel.detectionBlock = {
                (hotword: STTweetHotWord, text: String!, protocolString: String!, range: NSRange) -> Void in
                //do something here
        }
```

should work. (not tested)

**Comment by humblehacker** [comment]
This works:

```Swift
        label.detectionBlock = {
            hotword, string, prot, range in
            NSLog("%@", string)
        }
```
