### ISSUE TITLE
Emoticons cropped vertically

### ISSUE THREAD

**Issue by ashack293** [SebastienThiebaud/STTweetLabel#134]
See screenshot. The frame in this example has a height of 60. I was unable to reproduce this in the sample app, so I suspect that using a non-system font is the source of the issue.
![screen shot 2015-04-28 at 12 08 31 pm](https://cloud.githubusercontent.com/assets/89250/7374893/d5811ac2-eda2-11e4-8852-b1e9008c6922.png)

**Comment by ashack293** [comment]
In the screenshot below, the STTweetLabel is completely unstyled, so the issue definitely seems to be caused by changing the font. Would forcing the emoji to be a system font fix the issue perhaps?

![screen shot 2015-04-28 at 12 44 40 pm](https://cloud.githubusercontent.com/assets/89250/7375125/88cfb54c-eda4-11e4-8f3f-b56b8a307951.png)

**Comment by SebastienThiebaud** [comment]
Hey @ashack293 

We're gonna take a look at it, but it would be easier for us to fix that if you could send us your sample code. Thanks.

**Comment by ashack293** [comment]
My text styling is controlled in a way that is not conducive to copy-pasting a snippet, however I've fixed the issue by applying an NSParagraphStyle and explicitly setting a minimumLineHeight:

```objective-c
NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
paragraphStyle.lineSpacing = 3;
paragraphStyle.lineBreakMode = NSLineBreakByWordWrapping;
paragraphStyle.maximumLineHeight = 18;
paragraphStyle.minimumLineHeight = 16;
```

**Comment by SebastienThiebaud** [comment]
Can you copy/paste the code where you instantiate STTweetLabel, set the attributes and text please? I'm just wondering if you set the attributes after setting the text.

**Comment by ashack293** [comment]
Sure, here you go:

````objective-c 
    self.commentLabel = [[STTweetLabel alloc] initWithFrame:CGRectMake(55, 22, 260, 60)];
    __weak typeof(self) weakSelf = self; 
    [self.commentLabel setDetectionBlock:^(STTweetHotWord hotWord, NSString *string, NSString *protocol, NSRange range) {
        [weakSelf.delegate detectionBlockHandler:hotWord string:string protocol:protocol range:range];
    }];
    self.commentLabel.text = commentString;
    [self.delegate setSTTweetLabelAttributes:self.commentLabel];
````

**Comment by Reapert** [comment]
@ashack293 can you also write the what is inside the commentString ?

**Comment by sumitmundra** [comment]
can you told me where can i set the paragraphStyle
