### ISSUE TITLE
How to set attributed text to STTweetLabel

### ISSUE THREAD

**Issue by andr3a88** [SebastienThiebaud/STTweetLabel#138]
I tried to assign an attributed string to the label with the following code, but the text appears without attributes. If I try with a UILabel works correctly. it may not conflict with STTweetLabel?
```
        NSMutableAttributedString *feedAttributed = [[NSMutableAttributedString alloc] initWithString:@""];
        [feedAttributed appendAttributedString:postAuthorAttributed];
        [feedAttributed appendAttributedString:postedOnAttributed];
        [feedAttributed appendAttributedString:postTextAttributed];
    
        self.label.attributedText = feedAttributed;
```

**Comment by SebastienThiebaud** [comment]
You're not supposed to use an attributed string with STTweetLabel. This project expects to get a plain string only.
