### ISSUE TITLE
Handler which contains a dot detects incorrectly

### ISSUE THREAD

**Issue by romanvbabenko** [SebastienThiebaud/STTweetLabel#140]
e.g. @first.two detects as only "@first", without ".two" part on detection block

seems like a bug

**Comment by SebastienThiebaud** [comment]
It is not a bug, `.` character isn't allowed.

**Comment by romanvbabenko** [comment]
Instagram allow dot as a part of username, so according to your answer STTwetLabel cannot present handles like that correctly, right? If it's right, then it's bad.

**Comment by SebastienThiebaud** [comment]
Maybe you haven't see but the name of this repository is `STTweetLabel` and was designed for a Twitter client, not Instagram client. If you want to allow a `.` in the handle, please fork this repository and change the regex.

**Comment by cenksk** [comment]
[validCharactersSet addCharactersInString:@"_."]; this is solve your issue
