### ISSUE TITLE
doesn't work with autolayout

### ISSUE THREAD

**Issue by caofei10119** [SebastienThiebaud/STTweetLabel#144]
I have added STTweetLabel in table view cell and my cell height is supposed to be calculated automatically once auto-layout constraints are self satisfied.
Actually it works well when I use UILabel however height is wrong when I replace with STTweetLabel.
so I added this label above of UILabel so that it can match the same size with UILabel that is constrained. it works but I don't like this way as I need one more label for height calculation.
any idea to improve it?

**Comment by alexdd55** [comment]
Did you check #74 ? Sounds similar to me

**Comment by caofei10119** [comment]
I tried with 3.1.21 but it is still not compliance with self satisfied constraints. doesn't work
